### PR TITLE
Update steam.cpp

### PR DESCRIPTION
**Pull request by Siddhesh786**
I agree that my contributions are licensed under the Individual Contributor License Agreement V4.0 ("CLA") as stated in https://github.com/igarastudio/cla/blob/main/cla.md

I have signed the CLA following the steps given in https://github.com/igarastudio/cla#signing

### CODE REVIEW

**Comment by dacap** [comment]
Hi @Siddhesh786, could you explain what is this change about?

**Comment by Siddhesh786** [comment]
> Hi @Siddhesh786, could you explain what is this change about?
The changes are: 

1. Namespace Encapsulation: Typedefs and function pointer declarations are encapsulated within the Impl class to prevent polluting the global namespace.

2. Smart Pointers  :   CallbackMsg_t now uses std::unique_ptr to manage memory automatically.

3. Centralized Error Handling  :   getProc handles GETPROC retrieval, making the code cleaner and easier to debug.

4. General Improvements: Assertions and logging mechanisms ensure that the code can handle and report errors gracefully.

**Comment by dacap** [comment]
It looks like you have created this patch from GitHub or probably without compiling it (you have to define `-DENABLE_STEAM=ON` when using cmake to compile steam.cpp).

> Namespace Encapsulation: Typedefs and function pointer declarations are encapsulated within the Impl class to prevent polluting the global namespace.

There is no need as the functions are declared/used just in this file.

> Smart Pointers : CallbackMsg_t now uses std::unique_ptr to manage memory automatically.

Better than smart pointers are value/structures as we are already using (just a `CallbackMsg_t msg`).

Other issues: The CLA wasn't yet signed in case you want to continue with this patch, and the commit summary and description must be improved.

Here a list of compilation errors just because the types were removed:
```
src/steam/steam.cpp:153:3: error: unknown type name 'HSteamPipe'
  HSteamPipe m_pipe = 0;
  ^
src/steam/steam.cpp:156:3: error: unknown type name 'SteamAPI_ManualDispatch_RunFrame_Func'
  SteamAPI_ManualDispatch_RunFrame_Func SteamAPI_ManualDispatch_RunFrame = nullptr;
  ^
src/steam/steam.cpp:157:3: error: unknown type name 'SteamAPI_ManualDispatch_GetNextCallback_Func'
  SteamAPI_ManualDispatch_GetNextCallback_Func SteamAPI_ManualDispatch_GetNextCallback = nullptr;
  ^
src/steam/steam.cpp:158:3: error: unknown type name 'SteamAPI_ManualDispatch_FreeLastCallback_Func'
  SteamAPI_ManualDispatch_FreeLastCallback_Func SteamAPI_ManualDispatch_FreeLastCallback = nullptr;
  ^
src/steam/steam.cpp:22:92: error: use of undeclared identifier 'STEAM_API_DLL_FILENAME'
    m_steamLib = base::load_dll(base::join_path(base::get_file_path(base::get_app_path()), STEAM_API_DLL_FILENAME));
                                                                                           ^
src/steam/steam.cpp:33:38: error: use of undeclared identifier 'SteamAPI_Shutdown_Func'; did you mean 'SteamAPI_Shutdown'?
    auto SteamAPI_Shutdown = getProc<SteamAPI_Shutdown_Func>("SteamAPI_Shutdown");
                                     ^~~~~~~~~~~~~~~~~~~~~~
                                     SteamAPI_Shutdown
src/steam/steam.cpp:33:10: note: 'SteamAPI_Shutdown' declared here
    auto SteamAPI_Shutdown = getProc<SteamAPI_Shutdown_Func>("SteamAPI_Shutdown");
         ^
src/steam/steam.cpp:33:38: error: variable 'SteamAPI_Shutdown' declared with deduced type 'auto' cannot appear in its own initializer
    auto SteamAPI_Shutdown = getProc<SteamAPI_Shutdown_Func>("SteamAPI_Shutdown");
                                     ^
src/steam/steam.cpp:55:21: error: use of undeclared identifier 'CallbackMsg_t'
    std::unique_ptr<CallbackMsg_t> msg = std::make_unique<CallbackMsg_t>();
                    ^
src/steam/steam.cpp:55:59: error: use of undeclared identifier 'CallbackMsg_t'
    std::unique_ptr<CallbackMsg_t> msg = std::make_unique<CallbackMsg_t>();
                                                          ^
src/steam/steam.cpp:59:14: error: use of undeclared identifier 'kSteamServersDisconnected'
        case kSteamServersDisconnected:
             ^
src/steam/steam.cpp:60:14: error: use of undeclared identifier 'kSteamUndocumentedLastCallback'
        case kSteamUndocumentedLastCallback:
             ^
src/steam/steam.cpp:64:14: error: use of undeclared identifier 'kScreenshotReady'
        case kScreenshotReady: {
             ^
src/steam/steam.cpp:66:51: error: use of undeclared identifier 'SteamAPI_SteamUtils_v009_Func'; did you mean 'SteamAPI_SteamUtils_v009'?
          auto SteamAPI_SteamUtils_v009 = getProc<SteamAPI_SteamUtils_v009_Func>("SteamAPI_SteamUtils_v009");
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                  SteamAPI_SteamUtils_v009
src/steam/steam.cpp:66:16: note: 'SteamAPI_SteamUtils_v009' declared here
          auto SteamAPI_SteamUtils_v009 = getProc<SteamAPI_SteamUtils_v009_Func>("SteamAPI_SteamUtils_v009");
               ^
src/steam/steam.cpp:66:51: error: variable 'SteamAPI_SteamUtils_v009' declared with deduced type 'auto' cannot appear in its own initializer
          auto SteamAPI_SteamUtils_v009 = getProc<SteamAPI_SteamUtils_v009_Func>("SteamAPI_SteamUtils_v009");
                                                  ^
src/steam/steam.cpp:67:56: error: use of undeclared identifier 'SteamAPI_ISteamUtils_GetAppID_Func'; did you mean 'SteamAPI_ISteamUtils_GetAppID'?
          auto SteamAPI_ISteamUtils_GetAppID = getProc<SteamAPI_ISteamUtils_GetAppID_Func>("SteamAPI_ISteamUtils_GetAppID");
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                       SteamAPI_ISteamUtils_GetAppID
src/steam/steam.cpp:67:16: note: 'SteamAPI_ISteamUtils_GetAppID' declared here
          auto SteamAPI_ISteamUtils_GetAppID = getProc<SteamAPI_ISteamUtils_GetAppID_Func>("SteamAPI_ISteamUtils_GetAppID");
               ^
src/steam/steam.cpp:67:56: error: variable 'SteamAPI_ISteamUtils_GetAppID' declared with deduced type 'auto' cannot appear in its own initializer
          auto SteamAPI_ISteamUtils_GetAppID = getProc<SteamAPI_ISteamUtils_GetAppID_Func>("SteamAPI_ISteamUtils_GetAppID");
                                                       ^
src/steam/steam.cpp:70:13: error: unknown type name 'ISteamUtils'
            ISteamUtils* utils = SteamAPI_SteamUtils_v009();
            ^
src/steam/steam.cpp:92:37: error: use of undeclared identifier 'SteamAPI_SteamScreenshots_v003_Func'
    auto SteamScreenshots = getProc<SteamAPI_SteamScreenshots_v003_Func>("SteamAPI_SteamScreenshots_v003");
                                    ^
src/steam/steam.cpp:93:36: error: use of undeclared identifier 'SteamAPI_ISteamScreenshots_WriteScreenshot_Func'
    auto WriteScreenshot = getProc<SteamAPI_ISteamScreenshots_WriteScreenshot_Func>("SteamAPI_ISteamScreenshots_WriteScreenshot");
```

**Comment by Siddhesh786** [comment]
Ohh really sorry... I will correct my mistake!!!

**Pull request closed without merging**
