### PR TITLE
WIP initial attempt at tag userdata, does not work

### PR DESCRIPTION
**Pull request by sparr**
My goal here is to add userdata functionality to tags, as currently exists for cels, layers, and slices. The biggest hiccup was that the tag properties window isn't as fancifully defined as the others, but I think I got over that. Now everything works fine up until you actually change the userdata on a tag, at which point the change doesn't save. I would appreciate any insight on what bit of functionality I might have missed implementing.

### CODE REVIEW

**Comment by dacap** [comment]
Hi @sparr, please check the [CLA signing process](https://github.com/aseprite/opensource/blob/master/sign-cla.md#sign-the-cla).

**Comment by dacap** [comment]
I will try to review this PR soon and try to integrated it into `master` if it's possible and with a patch to the issues you're saying.

**Comment by jestarray** [comment]
dose this also address the problems with tags and scripting as mentioned here: https://github.com/aseprite/aseprite/issues/2487 ?

**Comment by dacap** [comment]
About this PR we will merge some of these changes + fixes for the future release v1.3. Thanks @sparr

**Comment by sparr** [comment]
You're welcome. Thanks for taking a look. I am glad at least some of this will be of use. I wish I had been able to see this through to completion.

**Comment by dacap** [comment]
I'm reviewing some old PRs, this was finally merged with https://github.com/aseprite/aseprite/commit/55a37d0e6b297e7b833fb502d8291de5530d2863

**Pull request closed without merging**
