### PR TITLE
Fixes #2653 by modifying installation instructions for windows

### LINKED ISSUE #2653: "ninja aseprite" causes errors, and doesn't compile
I am currently trying to compile the latest version of Aseprite on PopOS 20.04 LTS, and when I run "ninja aseprite", I get this log of errors. 

```
[5/710] Building CXX object laf/os/CMakeFiles/laf-os.dir/skia/skia_surface.cpp.o
FAILED: laf/os/CMakeFiles/laf-os.dir/skia/skia_surface.cpp.o 
/usr/bin/c++  -DCMARK_STATIC_DEFINE -DGR_GL_FUNCTION_TYPE=__stdcall -DHAVE_CONFIG_H -DLAF_FREETYPE -DLAF_SKIA -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_FORCE_DISTANCE_FIELD_TEXT=0 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_INTERNAL -DSK_R32_SHIFT=16 -DSK_SAMPLES_FOR_X -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=0 -DSK_SUPPORT_OPENCL=0 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/libwebp/src -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/harfbuzz/src -I../third_party/giflib/lib -I../third_party/jpeg -Ithird_party/cmark -I../third_party/curl/include -I../third_party/simpleini -I../src -I../laf -Ilaf -I../laf/third_party/stringencoders/src -I/home/brent/deps/skia -I/home/brent/deps/skia/include/config -I/home/brent/deps/skia/include/core -I/home/brent/deps/skia/include/utils -I/home/brent/deps/skia/include/codec -I/home/brent/deps/skia/include/gpu -I/home/brent/deps/skia/src/gpu -I/home/brent/deps/skia/third_party/skcms -Ithird_party/freetype2/include -O2 -g -DNDEBUG   -std=c++11 -MD -MT laf/os/CMakeFiles/laf-os.dir/skia/skia_surface.cpp.o -MF laf/os/CMakeFiles/laf-os.dir/skia/skia_surface.cpp.o.d -o laf/os/CMakeFiles/laf-os.dir/skia/skia_surface.cpp.o -c ../laf/os/skia/skia_surface.cpp
In file included from ../laf/os/skia/skia_surface.cpp:12:
../laf/os/skia/skia_surface.h:28:10: fatal error: include/private/SkColorData.h: No such file or directory
   28 | #include "include/private/SkColorData.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[6/710] Building CXX object laf/os/CMakeFiles/laf-os.dir/skia/skia_window_x11.cpp.o
FAILED: laf/os/CMakeFiles/laf-os.dir/skia/skia_window_x11.cpp.o 
/usr/bin/c++  -DCMARK_STATIC_DEFINE -DGR_GL_FUNCTION_TYPE=__stdcall -DHAVE_CONFIG_H -DLAF_FREETYPE -DLAF_SKIA -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_FORCE_DISTANCE_FIELD_TEXT=0 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_INTERNAL -DSK_R32_SHIFT=16 -DSK_SAMPLES_FOR_X -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=0 -DSK_SUPPORT_OPENCL=0 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/libwebp/src -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/harfbuzz/src -I../third_party/giflib/lib -I../third_party/jpeg -Ithird_party/cmark -I../third_party/curl/include -I../third_party/simpleini -I../src -I../laf -Ilaf -I../laf/third_party/stringencoders/src -I/home/brent/deps/skia -I/home/brent/deps/skia/include/config -I/home/brent/deps/skia/include/core -I/home/brent/deps/skia/include/utils -I/home/brent/deps/skia/include/codec -I/home/brent/deps/skia/include/gpu -I/home/brent/deps/skia/src/gpu -I/home/brent/deps/skia/third_party/skcms -Ithird_party/freetype2/include -O2 -g -DNDEBUG   -std=c++11 -MD -MT laf/os/CMakeFiles/laf-os.dir/skia/skia_window_x11.cpp.o -MF laf/os/CMakeFiles/laf-os.dir/skia/skia_window_x11.cpp.o.d -o laf/os/CMakeFiles/laf-os.dir/skia/skia_window_x11.cpp.o -c ../laf/os/skia/skia_window_x11.cpp
In file included from ../laf/os/skia/resize_surface.h:12,
                 from ../laf/os/skia/skia_window_x11.h:14,
                 from ../laf/os/skia/skia_window_x11.cpp:11:
../laf/os/skia/skia_surface.h:28:10: fatal error: include/private/SkColorData.h: No such file or directory
   28 | #include "include/private/SkColorData.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[7/710] Building CXX object laf/os/CMakeFiles/laf-os.dir/skia/skia_draw_text.cpp.o
FAILED: laf/os/CMakeFiles/laf-os.dir/skia/skia_draw_text.cpp.o 
/usr/bin/c++  -DCMARK_STATIC_DEFINE -DGR_GL_FUNCTION_TYPE=__stdcall -DHAVE_CONFIG_H -DLAF_FREETYPE -DLAF_SKIA -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_FORCE_DISTANCE_FIELD_TEXT=0 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_INTERNAL -DSK_R32_SHIFT=16 -DSK_SAMPLES_FOR_X -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=0 -DSK_SUPPORT_OPENCL=0 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/libwebp/src -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/harfbuzz/src -I../third_party/giflib/lib -I../third_party/jpeg -Ithird_party/cmark -I../third_party/curl/include -I../third_party/simpleini -I../src -I../laf -Ilaf -I../laf/third_party/stringencoders/src -I/home/brent/deps/skia -I/home/brent/deps/skia/include/config -I/home/brent/deps/skia/include/core -I/home/brent/deps/skia/include/utils -I/home/brent/deps/skia/include/codec -I/home/brent/deps/skia/include/gpu -I/home/brent/deps/skia/src/gpu -I/home/brent/deps/skia/third_party/skcms -Ithird_party/freetype2/include -O2 -g -DNDEBUG   -std=c++11 -MD -MT laf/os/CMakeFiles/laf-os.dir/skia/skia_draw_text.cpp.o -MF laf/os/CMakeFiles/laf-os.dir/skia/skia_draw_text.cpp.o.d -o laf/os/CMakeFiles/laf-os.dir/skia/skia_draw_text.cpp.o -c ../laf/os/skia/skia_draw_text.cpp
In file included from ../laf/os/skia/skia_draw_text.cpp:14:
../laf/os/skia/skia_surface.h:28:10: fatal error: include/private/SkColorData.h: No such file or directory
   28 | #include "include/private/SkColorData.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[8/710] Building CXX object laf/os/CMakeFiles/laf-os.dir/skia/skia_draw_text_with_shaper.cpp.o
FAILED: laf/os/CMakeFiles/laf-os.dir/skia/skia_draw_text_with_shaper.cpp.o 
/usr/bin/c++  -DCMARK_STATIC_DEFINE -DGR_GL_FUNCTION_TYPE=__stdcall -DHAVE_CONFIG_H -DLAF_FREETYPE -DLAF_SKIA -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_FORCE_DISTANCE_FIELD_TEXT=0 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_INTERNAL -DSK_R32_SHIFT=16 -DSK_SAMPLES_FOR_X -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=0 -DSK_SUPPORT_OPENCL=0 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/libwebp/src -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/harfbuzz/src -I../third_party/giflib/lib -I../third_party/jpeg -Ithird_party/cmark -I../third_party/curl/include -I../third_party/simpleini -I../src -I../laf -Ilaf -I../laf/third_party/stringencoders/src -I/home/brent/deps/skia -I/home/brent/deps/skia/include/config -I/home/brent/deps/skia/include/core -I/home/brent/deps/skia/include/utils -I/home/brent/deps/skia/include/codec -I/home/brent/deps/skia/include/gpu -I/home/brent/deps/skia/src/gpu -I/home/brent/deps/skia/third_party/skcms -Ithird_party/freetype2/include -O2 -g -DNDEBUG   -std=c++11 -MD -MT laf/os/CMakeFiles/laf-os.dir/skia/skia_draw_text_with_shaper.cpp.o -MF laf/os/CMakeFiles/laf-os.dir/skia/skia_draw_text_with_shaper.cpp.o.d -o laf/os/CMakeFiles/laf-os.dir/skia/skia_draw_text_with_shaper.cpp.o -c ../laf/os/skia/skia_draw_text_with_shaper.cpp
In file included from ../laf/os/skia/skia_draw_text_with_shaper.cpp:14:
../laf/os/skia/skia_surface.h:28:10: fatal error: include/private/SkColorData.h: No such file or directory
   28 | #include "include/private/SkColorData.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[9/710] Building CXX object laf/os/CMakeFiles/laf-os.dir/skia/resize_surface.cpp.o
FAILED: laf/os/CMakeFiles/laf-os.dir/skia/resize_surface.cpp.o 
/usr/bin/c++  -DCMARK_STATIC_DEFINE -DGR_GL_FUNCTION_TYPE=__stdcall -DHAVE_CONFIG_H -DLAF_FREETYPE -DLAF_SKIA -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_FORCE_DISTANCE_FIELD_TEXT=0 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_INTERNAL -DSK_R32_SHIFT=16 -DSK_SAMPLES_FOR_X -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=0 -DSK_SUPPORT_OPENCL=0 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/libwebp/src -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/harfbuzz/src -I../third_party/giflib/lib -I../third_party/jpeg -Ithird_party/cmark -I../third_party/curl/include -I../third_party/simpleini -I../src -I../laf -Ilaf -I../laf/third_party/stringencoders/src -I/home/brent/deps/skia -I/home/brent/deps/skia/include/config -I/home/brent/deps/skia/include/core -I/home/brent/deps/skia/include/utils -I/home/brent/deps/skia/include/codec -I/home/brent/deps/skia/include/gpu -I/home/brent/deps/skia/src/gpu -I/home/brent/deps/skia/third_party/skcms -Ithird_party/freetype2/include -O2 -g -DNDEBUG   -std=c++11 -MD -MT laf/os/CMakeFiles/laf-os.dir/skia/resize_surface.cpp.o -MF laf/os/CMakeFiles/laf-os.dir/skia/resize_surface.cpp.o.d -o laf/os/CMakeFiles/laf-os.dir/skia/resize_surface.cpp.o -c ../laf/os/skia/resize_surface.cpp
In file included from ../laf/os/skia/resize_surface.h:12,
                 from ../laf/os/skia/resize_surface.cpp:12:
../laf/os/skia/skia_surface.h:28:10: fatal error: include/private/SkColorData.h: No such file or directory
   28 | #include "include/private/SkColorData.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[10/710] Building CXX object laf/os/CMakeFiles/laf-os.dir/skia/skia_display.cpp.o
FAILED: laf/os/CMakeFiles/laf-os.dir/skia/skia_display.cpp.o 
/usr/bin/c++  -DCMARK_STATIC_DEFINE -DGR_GL_FUNCTION_TYPE=__stdcall -DHAVE_CONFIG_H -DLAF_FREETYPE -DLAF_SKIA -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_FORCE_DISTANCE_FIELD_TEXT=0 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_INTERNAL -DSK_R32_SHIFT=16 -DSK_SAMPLES_FOR_X -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=0 -DSK_SUPPORT_OPENCL=0 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/libwebp/src -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/harfbuzz/src -I../third_party/giflib/lib -I../third_party/jpeg -Ithird_party/cmark -I../third_party/curl/include -I../third_party/simpleini -I../src -I../laf -Ilaf -I../laf/third_party/stringencoders/src -I/home/brent/deps/skia -I/home/brent/deps/skia/include/config -I/home/brent/deps/skia/include/core -I/home/brent/deps/skia/include/utils -I/home/brent/deps/skia/include/codec -I/home/brent/deps/skia/include/gpu -I/home/brent/deps/skia/src/gpu -I/home/brent/deps/skia/third_party/skcms -Ithird_party/freetype2/include -O2 -g -DNDEBUG   -std=c++11 -MD -MT laf/os/CMakeFiles/laf-os.dir/skia/skia_display.cpp.o -MF laf/os/CMakeFiles/laf-os.dir/skia/skia_display.cpp.o.d -o laf/os/CMakeFiles/laf-os.dir/skia/skia_display.cpp.o -c ../laf/os/skia/skia_display.cpp
In file included from ../laf/os/skia/resize_surface.h:12,
                 from ../laf/os/skia/skia_window_x11.h:14,
                 from ../laf/os/skia/skia_window.h:16,
                 from ../laf/os/skia/skia_display.h:15,
                 from ../laf/os/skia/skia_display.cpp:12:
../laf/os/skia/skia_surface.h:28:10: fatal error: include/private/SkColorData.h: No such file or directory
   28 | #include "include/private/SkColorData.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[11/710] Building CXX object laf/os/CMakeFiles/laf-os.dir/skia/os.cpp.o
FAILED: laf/os/CMakeFiles/laf-os.dir/skia/os.cpp.o 
/usr/bin/c++  -DCMARK_STATIC_DEFINE -DGR_GL_FUNCTION_TYPE=__stdcall -DHAVE_CONFIG_H -DLAF_FREETYPE -DLAF_SKIA -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_FORCE_DISTANCE_FIELD_TEXT=0 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_INTERNAL -DSK_R32_SHIFT=16 -DSK_SAMPLES_FOR_X -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=0 -DSK_SUPPORT_OPENCL=0 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/libwebp/src -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/harfbuzz/src -I../third_party/giflib/lib -I../third_party/jpeg -Ithird_party/cmark -I../third_party/curl/include -I../third_party/simpleini -I../src -I../laf -Ilaf -I../laf/third_party/stringencoders/src -I/home/brent/deps/skia -I/home/brent/deps/skia/include/config -I/home/brent/deps/skia/include/core -I/home/brent/deps/skia/include/utils -I/home/brent/deps/skia/include/codec -I/home/brent/deps/skia/include/gpu -I/home/brent/deps/skia/src/gpu -I/home/brent/deps/skia/third_party/skcms -Ithird_party/freetype2/include -O2 -g -DNDEBUG   -std=c++11 -MD -MT laf/os/CMakeFiles/laf-os.dir/skia/os.cpp.o -MF laf/os/CMakeFiles/laf-os.dir/skia/os.cpp.o.d -o laf/os/CMakeFiles/laf-os.dir/skia/os.cpp.o -c ../laf/os/skia/os.cpp
In file included from ../laf/os/skia/resize_surface.h:12,
                 from ../laf/os/skia/skia_window_x11.h:14,
                 from ../laf/os/skia/skia_window.h:16,
                 from ../laf/os/skia/skia_display.h:15,
                 from ../laf/os/skia/skia_system.h:16,
                 from ../laf/os/skia/os.cpp:11:
../laf/os/skia/skia_surface.h:28:10: fatal error: include/private/SkColorData.h: No such file or directory
   28 | #include "include/private/SkColorData.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[16/710] Building CXX object laf/os/CMakeFiles/laf-os.dir/skia/skia_color_space.cpp.o
FAILED: laf/os/CMakeFiles/laf-os.dir/skia/skia_color_space.cpp.o 
/usr/bin/c++  -DCMARK_STATIC_DEFINE -DGR_GL_FUNCTION_TYPE=__stdcall -DHAVE_CONFIG_H -DLAF_FREETYPE -DLAF_SKIA -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_FORCE_DISTANCE_FIELD_TEXT=0 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_INTERNAL -DSK_R32_SHIFT=16 -DSK_SAMPLES_FOR_X -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=0 -DSK_SUPPORT_OPENCL=0 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/libwebp/src -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/harfbuzz/src -I../third_party/giflib/lib -I../third_party/jpeg -Ithird_party/cmark -I../third_party/curl/include -I../third_party/simpleini -I../src -I../laf -Ilaf -I../laf/third_party/stringencoders/src -I/home/brent/deps/skia -I/home/brent/deps/skia/include/config -I/home/brent/deps/skia/include/core -I/home/brent/deps/skia/include/utils -I/home/brent/deps/skia/include/codec -I/home/brent/deps/skia/include/gpu -I/home/brent/deps/skia/src/gpu -I/home/brent/deps/skia/third_party/skcms -Ithird_party/freetype2/include -O2 -g -DNDEBUG   -std=c++11 -MD -MT laf/os/CMakeFiles/laf-os.dir/skia/skia_color_space.cpp.o -MF laf/os/CMakeFiles/laf-os.dir/skia/skia_color_space.cpp.o.d -o laf/os/CMakeFiles/laf-os.dir/skia/skia_color_space.cpp.o -c ../laf/os/skia/skia_color_space.cpp
../laf/os/skia/skia_color_space.cpp: In constructor ‘os::SkiaColorSpace::SkiaColorSpace(const ColorSpacePtr&)’:
../laf/os/skia/skia_color_space.cpp:59:46: error: ‘SkNamedGamut’ has not been declared
   59 |           m_skcs = SkColorSpace::MakeRGB(fn, SkNamedGamut::kSRGB);
      |                                              ^~~~~~~~~~~~
../laf/os/skia/skia_color_space.cpp:91:56: error: no matching function for call to ‘SkColorSpace::MakeRGB(skcms_TransferFunction&, skcms_Matrix3x3&)’
   91 |           m_skcs = SkColorSpace::MakeRGB(skFn, toXYZD50);
      |                                                        ^
In file included from ../laf/os/skia/skia_color_space.h:14,
                 from ../laf/os/skia/skia_color_space.cpp:11:
/home/brent/deps/skia/include/core/SkColorSpace.h:101:32: note: candidate: ‘static sk_sp<SkColorSpace> SkColorSpace::MakeRGB(SkColorSpace::RenderTargetGamma, SkColorSpace::Gamut)’
  101 |     static sk_sp<SkColorSpace> MakeRGB(RenderTargetGamma gamma, Gamut gamut);
      |                                ^~~~~~~
/home/brent/deps/skia/include/core/SkColorSpace.h:101:58: note:   no known conversion for argument 1 from ‘skcms_TransferFunction’ to ‘SkColorSpace::RenderTargetGamma’
  101 |     static sk_sp<SkColorSpace> MakeRGB(RenderTargetGamma gamma, Gamut gamut);
      |                                        ~~~~~~~~~~~~~~~~~~^~~~~
/home/brent/deps/skia/include/core/SkColorSpace.h:102:32: note: candidate: ‘static sk_sp<SkColorSpace> SkColorSpace::MakeRGB(SkColorSpace::RenderTargetGamma, const SkMatrix44&)’
  102 |     static sk_sp<SkColorSpace> MakeRGB(RenderTargetGamma gamma, const SkMatrix44& toXYZD50);
      |                                ^~~~~~~
/home/brent/deps/skia/include/core/SkColorSpace.h:102:58: note:   no known conversion for argument 1 from ‘skcms_TransferFunction’ to ‘SkColorSpace::RenderTargetGamma’
  102 |     static sk_sp<SkColorSpace> MakeRGB(RenderTargetGamma gamma, const SkMatrix44& toXYZD50);
      |                                        ~~~~~~~~~~~~~~~~~~^~~~~
/home/brent/deps/skia/include/core/SkColorSpace.h:103:32: note: candidate: ‘static sk_sp<SkColorSpace> SkColorSpace::MakeRGB(const SkColorSpaceTransferFn&, SkColorSpace::Gamut)’
  103 |     static sk_sp<SkColorSpace> MakeRGB(const SkColorSpaceTransferFn& coeffs, Gamut gamut);
      |                                ^~~~~~~
/home/brent/deps/skia/include/core/SkColorSpace.h:103:70: note:   no known conversion for argument 1 from ‘skcms_TransferFunction’ to ‘const SkColorSpaceTransferFn&’
  103 |     static sk_sp<SkColorSpace> MakeRGB(const SkColorSpaceTransferFn& coeffs, Gamut gamut);
      |                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/home/brent/deps/skia/include/core/SkColorSpace.h:104:32: note: candidate: ‘static sk_sp<SkColorSpace> SkColorSpace::MakeRGB(const SkColorSpaceTransferFn&, const SkMatrix44&)’
  104 |     static sk_sp<SkColorSpace> MakeRGB(const SkColorSpaceTransferFn& coeffs,
      |                                ^~~~~~~
/home/brent/deps/skia/include/core/SkColorSpace.h:104:70: note:   no known conversion for argument 1 from ‘skcms_TransferFunction’ to ‘const SkColorSpaceTransferFn&’
  104 |     static sk_sp<SkColorSpace> MakeRGB(const SkColorSpaceTransferFn& coeffs,
      |                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/home/brent/deps/skia/include/core/SkColorSpace.h:107:32: note: candidate: ‘static sk_sp<SkColorSpace> SkColorSpace::MakeRGB(SkGammaNamed, const SkMatrix44&)’
  107 |     static sk_sp<SkColorSpace> MakeRGB(SkGammaNamed gammaNamed, const SkMatrix44& toXYZD50);
      |                                ^~~~~~~
/home/brent/deps/skia/include/core/SkColorSpace.h:107:53: note:   no known conversion for argument 1 from ‘skcms_TransferFunction’ to ‘SkGammaNamed’
  107 |     static sk_sp<SkColorSpace> MakeRGB(SkGammaNamed gammaNamed, const SkMatrix44& toXYZD50);
      |                                        ~~~~~~~~~~~~~^~~~~~~~~~
../laf/os/skia/skia_color_space.cpp:94:42: error: ‘SkNamedTransferFn’ has not been declared
   94 |           m_skcs = SkColorSpace::MakeRGB(SkNamedTransferFn::kSRGB, toXYZD50);
      |                                          ^~~~~~~~~~~~~~~~~
../laf/os/skia/skia_color_space.cpp:117:39: error: cannot convert ‘skcms_TransferFunction*’ to ‘SkColorSpaceTransferFn*’
  117 |     if (m_skcs->isNumericalTransferFn(&fn) &&
      |                                       ^~~
      |                                       |
      |                                       skcms_TransferFunction*
In file included from ../laf/os/skia/skia_color_space.h:14,
                 from ../laf/os/skia/skia_color_space.cpp:11:
/home/brent/deps/skia/include/core/SkColorSpace.h:137:56: note:   initializing argument 1 of ‘bool SkColorSpace::isNumericalTransferFn(SkColorSpaceTransferFn*) const’
  137 |     bool isNumericalTransferFn(SkColorSpaceTransferFn* fn) const;
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~^~
../laf/os/skia/skia_color_space.cpp:118:26: error: cannot convert ‘skcms_Matrix3x3*’ to ‘SkMatrix44*’
  118 |         m_skcs->toXYZD50(&toXYZD50)) {
      |                          ^~~~~~~~~
      |                          |
      |                          skcms_Matrix3x3*
In file included from ../laf/os/skia/skia_color_space.h:14,
                 from ../laf/os/skia/skia_color_space.cpp:11:
/home/brent/deps/skia/include/core/SkColorSpace.h:143:31: note:   initializing argument 1 of ‘bool SkColorSpace::toXYZD50(SkMatrix44*) const’
  143 |     bool toXYZD50(SkMatrix44* toXYZD50) const;
      |                   ~~~~~~~~~~~~^~~~~~~~
[22/710] Building CXX object src/clip/CMakeFiles/clip.dir/clip_x11.cpp.o
ninja: build stopped: subcommand failed.
```

Is there a way to fix this?

### PR DESCRIPTION
**Pull request by w4ffl35**
I agree that my contributions are licensed under the Individual Contributor License Agreement V3.0 ("CLA") as stated in https://github.com/aseprite/sourcecode/blob/main/cla.md

I have signed the CLA following the steps given in https://github.com/aseprite/sourcecode/blob/main/sign-cla.md#sign-the-cla

### CODE REVIEW

**Comment by w4ffl35** [comment]
I don't want to sign the CLA, but this is the fix.

**Comment by dacap** [comment]
Sorry but `SKIA_LIBRARY_DIR` must point to `C:\deps\skia\out\Release-x64` (or `C:\deps\skia\out\Debug-x64`, etc.) and `SKIA_DIR` is the one that points to `C:\deps\skia`.

`SKIA_LIBRARY_DIR` is used to automatically find `skia.lib` and `skshaper.lib` libraries.

**Comment by w4ffl35** [comment]
@dacap IIRC when i compiled yesterday the program was attempting to look at `C:\deps\skia\out\Release-x64\out\Release-x64` so removing ``C:\deps\skia\` from the command allowed `out\Release-x64` to be correctly suffixed. Without changing this compile failed.

**Comment by dacap** [comment]
@w4ffl35 the default value (and expected value) of `SKIA_LIBRARY_DIR` is `${SKIA_DIR}/out/Release-x64` as [specified here](https://github.com/aseprite/laf/blob/7c819791e50116b54e0666dbf96822e0993d1d1f/cmake/FindSkia.cmake#L18)). But this variable is used only to autodetect [skia](https://github.com/aseprite/laf/blob/7c819791e50116b54e0666dbf96822e0993d1d1f/cmake/FindSkia.cmake#L23), [skshaper](https://github.com/aseprite/laf/blob/7c819791e50116b54e0666dbf96822e0993d1d1f/cmake/FindSkia.cmake#L33), [freetype2](https://github.com/aseprite/laf/blob/7c819791e50116b54e0666dbf96822e0993d1d1f/cmake/FindSkia.cmake#L36), and [harfbuzz](https://github.com/aseprite/laf/blob/7c819791e50116b54e0666dbf96822e0993d1d1f/cmake/FindSkia.cmake#L40) filenames (if you have those names already configured in your `CMakeCache.txt` file, it doesn't matter what value `SKIA_LIBRARY_DIR` has, it will works anyway because the variable is not used anymore)

All the details are here: https://github.com/aseprite/laf/blob/main/cmake/FindSkia.cmake

I'm locking this issue so the information can be useful for future users and less confusing. Even more, if you delete from `CMakeCache.txt` all your `SKIA_*` variables except `SKIA_DIR` (ponting to `C:/deps/skia`), you will see that `SKIA_LIBRARY_DIR` will be configured automatically to `${SKIA_DIR}/out/Release-x64` or `${SKIA_DIR}/out/Debug-x64`. This is what I always do (only configure SKIA_DIR, all other variables are automatically detected).

**Pull request closed without merging**
