### PR TITLE
pixly: dealing with cels smaller than the sprite

### PR DESCRIPTION
**Pull request by zed9h**
I could not test this branch `pixly-fix`, but I tested the commit on the branch `pixly`, which is based on `v1.1.5.7`; I am having problems to use your `master`, there seems to be some files missing in `src/observable/*`.

### CODE REVIEW

**Comment by dacap** [comment]
About the `observable` directory, it's because you have to do a `git submodule update --init` as a new submodule is in the repository.

**Comment by dacap** [comment]
Anyway I'll apply this PR as a patch.

**Comment by dacap** [comment]
Merged as a patch 99bd10dfbdb9d2579d57f0640db9526a988e6a2d

**Comment by zed9h** [comment]
Good one, I almost sent the patch on a message on the last PR :)

**Pull request closed without merging**
