### PR TITLE
Fixing Freetype and Harfbuzz system shared libraries support

### PR DESCRIPTION
**Pull request by winterheart**
Fixed linking system Freetype library issue #1453 and added support for system Harfbuzz.

### CODE REVIEW

**Comment by dacap** [comment]
Hi @winterheart, I'll take a look at this later. Anyway, the idea behind the `ft::open_stream()` function is that it uses `base::open_file_raw()` so you can load ttf fonts with unicode filenames. From what I see, that functionality would be lost with this patch, is that right?

**Comment by winterheart** [comment]
OK, I got the point. Can we use here FT_New_Memory_Face() instead?

**Comment by dacap** [comment]
I would prefer to use the `FILE` interface because it avoids to load the entire file on memory (at least that is what I think, I'm not 100% sure) and `Arial Unicode.ttf` is 23.3 MB on macOS.

From my point of view this is an issue on the freetype2 library, because their solution to create a customize `FT_Stream` requires their internal header files (and these files shouldn't internal in the first place). Maybe a freetype2 patch?

**Comment by winterheart** [comment]
@dacap hello again.
Can you review this try?

**Comment by dacap** [comment]
Hi @winterheart, sorry for my late response on this one, I'll try to review this after fixing some serious issues on Windows 10 for Surface devices.

**Pull request merged**
