### PR TITLE
Added swap checkerboard background colors command (#1812)

### PR DESCRIPTION
**Pull request by MorganDavid**
Added as a command with no default shortcut and no menu item.
https://github.com/aseprite/aseprite/issues/1812

### CODE REVIEW

**Comment by dacap** [comment]
After tha CLA process is finished, about this PR, not sure if the command should be called `SwapCheckerboardColors`, or `SwapCheckedBackgroundColors`, or `SwitchCheckedBackgroundColors` (like `SwitchColors`), or maybe just an argument for `SwitchColors` 🤔

**Comment by MorganDavid** [comment]
Personally, I think swap makes more sense, but to keep it consistent with `SwitchColors` I could change it to `SwitchCheckedBackgroundColors`? I thought about adding params to `SwitchColors` since the behaviour is similar but decided to make a new command because the usage in the application is very different. 

Also, am I doing anything wrong for the Travis CI build to fail?

**Comment by dacap** [comment]
Or don't worry, `SwapCheckerboardColors` it's fine 👍 , we can use it in that way (I might change the `SwitchColors` to `SwapColors` in a future with an alias).

**Comment by dacap** [comment]
About the CI, actually I've fixed it today, and I think this PR was forked from a commit that was already failing, so nothing to worry about.

**Comment by MorganDavid** [comment]
It seems my commits were from the wrong GitHub account, I'll close this and make a new PR.

**Pull request closed without merging**
