### PR TITLE
Add a way to create and delete tilesets using Lua

### LINKED ISSUE #3661: A way to create new and delete tilesets using Lua

### LINKED ISSUE #3662: A way to duplicate tilesets using Lua

### PR DESCRIPTION
**Pull request by martincapello**
Fix #3661 and fix #3662

### CODE REVIEW

**Comment by martincapello** [comment]
Now working in adding some lua tests for this

**Comment by dacap** [comment]
Probably I'll cherry pick the first commit of this PR, then merge any other added commit.

**Comment by dacap** [comment]
Merged in https://github.com/aseprite/aseprite/commit/9910ab73f05a8473d5c978b75101daa91dc84cae and https://github.com/aseprite/aseprite/commit/c299be50a54b1afa659c260d5f063e480e4f4a16, sorry if it's too early, I needed the Tilesets::getIndex() function (adding a new cmd to set the layer tileset here).

**Comment by dacap** [comment]
Forgot to mention, this will require an update to the API docs ([next-version branch](https://github.com/aseprite/api/tree/next-version)).

**Comment by martincapello** [comment]
> Probably I'll cherry pick the first _two commits_ of this PR, then merge any other added commit.

Sounds good, I actually made this draft to allow you do that.

**Comment by martincapello** [comment]
I was forgetting to update the documentation...

**Comment by dacap** [comment]
Merged 7e16b4964419dc1598a274927411cd386ffca4d5

**Pull request closed without merging**
