### PR TITLE
Add enable panning and zooming with an opened filter window (fix #2563)

### LINKED ISSUE #2563: Enable panning and zooming with an opened window
Enable panning and zooming (by pressing<kbd>mousewheel</kbd>) while replace color window is open.

This would be useful when previewing color changes before submitting them.

Gif below shows how you can pan and zoom while there no window, but cannot when window is open.
kST3cpbb3j

### Aseprite and System version

* Aseprite version: V.1.2.25-x64, Steam
* System: Windows

### PR DESCRIPTION
**Pull request by Gasparoken**
Replace Color, Color Curve, Outline, Convolution Matrix, etc are Filter Windows.

fix #2563

This fix enables:
- Panning and zooming.

Additional features for the future:
- Possibility to change the active Cel.

### CODE REVIEW

**Comment by dacap** [comment]
@martincapello could you please test this?

**Comment by martincapello** [comment]
It does enable panning and zooming while the filter window is opened. The only thing I noted is that the filter preview is applied to the current visible portion of the sprite, then if you preview the filter and then pan the viewport you will see that part of the sprite was not affected by the preview so you have to uncheck and check again the preview checkbox to refresh the viewport's image in its new position.

**Comment by martincapello** [comment]
Now it works like a charm! I just found a minor issue (not sure if it is an actual issue)...when some of the filter windows are open and the preview windows is also open, the preview window cannot be moved by dragging its title bar, however resizing is allowed, as well as clicking the buttons on the title bar. I think we could merge this and create a separate issue for the preview window glitches.

**Comment by Gasparoken** [comment]
Thank you!
About:
> ... when some of the filter windows are open and the preview windows is also open, the preview window cannot be moved by dragging its title bar, however resizing is allowed, as well as clicking the buttons on the title bar. I think we could merge this and create a separate issue for the preview window glitches.

Yes, it can be taken as another separate issue.

**Comment by dacap** [comment]
I don't know why this PR contains 6 commits, I'll review 181a0884417a0da4d96e24ab1e710c9e73fe22b2 only cherry-picking it.

**Comment by dacap** [comment]
> Sorry, I'm not sure why it happened.

Don't worry about this, I was able to cherry pick the commit. For the next time I would recommend you to avoid deleting/recreating the branch (checkout can be tricky and do things you don't expect). Instead you can try to do a [git rebase](https://git-scm.com/docs/git-rebase) with the latest `main` commit (anyway I would recommend you to backup the branch, e.g. create a local branch in the original commit before you rebase, because it's a complex operation that can fail with conflicts to solve, etc.). You could give a try to rebase with some local repo/tests before using it in production.

About the fix, it works great :+1: I'll merge it as it is. Then I have noticed some performance issues on Linux because it generates a lot of mouse messages for scrolling, so I'm planning to add some extra code to restart the preview after some timer (to consume/ignore several mouse movements).

**Comment by dacap** [comment]
Merged in 2369f36322bcfdebe4f16d87d5f3b4f3551cbfc7

**Pull request closed without merging**
