### PR TITLE
Make LibArchive as shared library dependency

### PR DESCRIPTION
**Pull request by winterheart**
Add -DUSE_SHARED_LIBARCHIVE option to enable shared library usage.

### CODE REVIEW

**Comment by ryandesign** [comment]
A similar fix was already submitted in #2523.

**Comment by ryandesign** [comment]
This would be a step toward fixing #1681.

**Comment by dacap** [comment]
Hi there! thanks @winterheart and @ryandesign, I'll review this soon in my Linux VM, I think I prefer this PR instead of #2523 because it adds only support for libarchive (and the webp is more complex, because there are incompatibilities between versions, what library to link, etc.).

**Comment by dacap** [comment]
This PR was closed automatically because we deleted the `master` branch (now know as `main` branch).

Anyway I'm not sure if we should keep adding more USE_SHARED flags or remove them all: #2843

From my point of view is that more options bring more problems.

**Comment by ISSOtm** [comment]
This allows working around an issue I have building Aseprite: I require `-DCMAKE_BUILD_TYPE=None` (and since Aseprite defaults to `RelWithDebInfo` if it is unspecified, I must specify it explicitly); however, `libarchive` rejects that option (it only defaults to `Debug` if the cache entry is unset... but Aseprite's own `CMakeLists.txt` prevents that.)

This relates to the points I made in https://github.com/aseprite/aseprite/issues/2843#issuecomment-1003416723.

**Pull request closed without merging**
