### PR TITLE
Added opacity field when exporting a cell

### PR DESCRIPTION
**Pull request by requizm**
Fix: #4511

### CODE REVIEW

**Comment by dacap** [comment]
Thanks @requizm, I'm not sure if we should export the opacity if it's 255. What do you think?

**Comment by dacap** [comment]
I'll merge this and remove the opacity when it's 255.

**Comment by requizm** [comment]
> Thanks @requizm, I'm not sure if we should export the opacity if it's 255. What do you think?

Why not? What is the disadvantage?

**Comment by dacap** [comment]
> Why not? What is the disadvantage?

I've added an extra change after the merge explaining the rationale behind this: https://github.com/aseprite/aseprite/commit/4e5dfa9d2c520b9e98dfc5b0fcd759df6a523b84

**Pull request merged**
