### PR TITLE
Fixed ftglyph.h not found when using external FreeType2

### PR DESCRIPTION
**Pull request by Mailaender**
For @openSUSE Linux I have to set `-DFREETYPE_INCLUDE_DIR=%{_includedir}/freetype2` so freetype is incorrect.

### CODE REVIEW

**Comment by dacap** [comment]
Hi @Mailaender, please check that this commit doesn't pass the Travis CI build https://travis-ci.org/aseprite/aseprite/builds/91203332

**Comment by Mailaender** [comment]
I redid this completely. https://build.opensuse.org/request/show/346257 with https://cmake.org/cmake/help/cmake2.6docs.html#module:FindFreetype

**Comment by dacap** [comment]
This should be fixed with #1035

**Comment by Mailaender** [comment]
Turns out it isn't. We still need
```patch
diff -Nur aseprite-1.1.5.6/src/ft/freetype_headers.h new/src/ft/freetype_headers.h
--- aseprite-1.1.5.6/src/ft/freetype_headers.h	2016-05-21 18:41:24.000000000 +0200
+++ new/src/ft/freetype_headers.h	2016-05-22 02:07:08.919513785 +0200
@@ -8,8 +8,8 @@
 #define FT_FREETYPE_HEADERS_H_INCLUDED
 #pragma once
 
-#include "freetype/ftglyph.h"
-#include "ft2build.h"
+#include <ft2build.h>
+#include FT_GLYPH_H
 #include FT_FREETYPE_H
 
 #endif
```

**Pull request closed without merging**
