### PR TITLE
Fix crash when saving tilemap's cel image

### LINKED ISSUE #4069: Tilemap cel image saveAs call leads to segmentation fault.
### Issue
When calling Image:SaveAs() on a image from a cel in a tilemap, a segmentation fault happens which leads to the app exiting.

### Reproduce

Run a script with the following code snippet with the attached [aseprite file](https://github.com/aseprite/aseprite/files/12719091/tilemap-crash.zip) open, and observe the app crash.
```lua
app.sprite.layers[1].cels[1].image:saveAs("image.png")
```

### Aseprite and System version

* Aseprite version: 1.3-rc6-x64 and commit 19b54ff
* System: Windows 10.0.19045

### PR DESCRIPTION
**Pull request by martincapello**
After applying this PR:
1) A script can save a cel's image from a tilemap layer without crashing Aseprite. 
2) The saved image is the rendered image using the tileset tiles for each tilemap index.
3) A new lua test is added. 

Fix #4069

### CODE REVIEW

**Comment by dacap** [comment]
Didn't review this, waiting for @Gasparoken, anyway it would be nice to add a note about any new sprite added in the `tests/sprites/README.md` file.

**Comment by Gasparoken** [comment]
I'll review this today. Sorry for the delay.

**Comment by Gasparoken** [comment]
Works great! I think the name `MakeStdTilemap` could be improved to describe:
"Make a blank sprite with Tilemap layer and specific Tileset"

**Comment by martincapello** [comment]
Would MakeStdTilemapSpriteWithTileset work?

**Comment by Gasparoken** [comment]
> Would `MakeStdTilemapSpriteWithTileset` work?

LGTM!😊

**Review by Gasparoken — APPROVED** [review]
LGTM! 🙌

**Pull request merged**
