### PR TITLE
Copy the slices to the duplicated sprite

### LINKED ISSUE #2564: The duplicated file will not contain slices
Currently the code to copy slices does not seem to be implemented.

https://github.com/aseprite/aseprite/blob/319733d30bea5723ae8c8734cd81f6db7011acba/src/app/doc.cpp#L513

The means of reproducing this problem is as follows.

---

Run `Sprite -> Duplicate...` from the aseprite's menu.

or

```Lua
-- Lua script
Sprite(otherSprite)
```

### Aseprite and System version

* Aseprite version: v1.2.25 portable
* System: macOS Mojave 10.14.6

### PR DESCRIPTION
**Pull request by sumibi-yakitori**
Closes #2564

### CODE REVIEW

**Comment by dacap** [comment]
Hi @sumibi-yakitori, thanks for your contribution, could you please follow the steps to [sign the CLA](https://github.com/aseprite/sourcecode/blob/master/sign-cla.md#sign-the-cla)?

Right now I'm not merging pull requests but in the following weeks I'll start reviewing all the pending patches.

**Comment by sumibi-yakitori** [comment]
@dacap 
I sent an email with the PR.

**Comment by dacap** [comment]
Thanks for the contribution @sumibi-yakitori, I'll merge this as it is. Anyway I think it needs some fixes (copying the slice color, and owner).

**Comment by dacap** [comment]
Oh sorry, I saw that there is a setUserData to copy the color and then the Slices::add() changes the owner. I think I'll merge this as it is.

**Pull request merged**
