### PR TITLE
Avoid dirent.d_type since it is not POSIX compatible.

### PR DESCRIPTION
**Pull request by opeter**
This fixes the empty file dialog bug on XFS/JFS/... from issue #951

### CODE REVIEW

**Comment by dacap** [comment]
Hi @opeter, thanks for this PR. Please check our [CLA signing process](https://github.com/aseprite/opensource/blob/master/sign-cla.md#sign-the-cla).

**Comment by opeter** [comment]
Hi @dacap, CLA signing process has been completed and merged a while ago.  (https://github.com/aseprite/opensource/pull/22)

What about the patch?  Seems like it would already fix two issues #1530 and #951.  Is there anything else I need to to from my side?

**Comment by dacap** [comment]
@opeter sorry for the late response in this one, I wasn't able to test the change in Ubuntu but I'll try to do it today.

**Comment by dacap** [comment]
As I cannot test XFS filesystem or exFAT right now, I'll merge the patch, I've tried on Ext4 and it works as usual so basically it can only fix things. Thanks for the contribution @opeter.

**Comment by dacap** [comment]
Cherry picked here 70f0496cd94741f3dc2ad4a962221807edbc89c7

**Pull request closed without merging**
