### PR TITLE
Add missing strings in language file (fix #2809)

### LINKED ISSUE #2809: Missing strings in language file
The following strings are missing in the standard `en.ini` language file:

<details>
<summary>Screenshot 1</summary>

image

</details>

<details>
<summary>Screenshot 2</summary>
  
image
  
</details>

<details>
<summary>Screenshot 3</summary>
  
image
  
</details>

<details>
<summary>Screenshot 4</summary>
  
image
  
</details>

<details>
<summary>Screenshot 5</summary>
  
image
  
</details>

<details>
<summary>Screenshot 6</summary>
  
image
  
</details>

<details>
<summary>Screenshot 7</summary>
  
image
  
</details>

<details>
<summary>Screenshot 8</summary>
  
image
  
</details>

What prevents them from being translated.

### Aseprite and System version

* Aseprite version: 1.2.27, portable dev
* System: Windows 11

### PR DESCRIPTION
**Pull request by iamOgunyinka**
During a language change, all user-friendly strings should reflect the new change. This PR adds more strings that allows this change to happen.

### CODE REVIEW

**Comment by dacap** [comment]
Thanks @iamOgunyinka, I'll see if I'm able to merge this in the following days. Actually #2809 was planned for v1.2.31 so the PR should be for `main` branch. I'll see if I can apply each commit into `main` first and then merge `main` into `beta`.

**Comment by dacap** [comment]
I'll merge this/cherry-pick commits after #3548 is done.

**Comment by dacap** [comment]
Finally merged https://github.com/aseprite/aseprite/commit/160a3f9a6ce54abeda53ad0138dd308a584bf35e (some commits were modified a little)

Thanks @iamOgunyinka for your help with the project.

**Comment by iamOgunyinka** [comment]
No worries, @dacap. It was a privilege working with you on Aseprite.

**Pull request closed without merging**
