### PR TITLE
Command for scrolling to center of canvas

### PR DESCRIPTION
**Pull request by tony**
Centers canvas.

Defaults to "C" key.

### CODE REVIEW

**Comment by tony** [comment]
@TheKK is this better

**Comment by TheKK** [comment]
Looks more clear to me :)

**Comment by dacap** [comment]
Thanks @tony, I'll merge this PR, I'm not sure about the `C` key, I might change it later (to something like `Shift+C` or `Space+C`)

**Comment by tony** [comment]
@dacap I'm fine w/ changing the default key.  I think Shift-C seems nice.

**Pull request merged**
