### PR TITLE
Fix SHE lib underlinking (fix issue #625).

### PR DESCRIPTION
**Pull request by winterheart**

### CODE REVIEW

**Comment by dacap** [comment]
Hi @winterheart, in which platform is this change needed? (so I can test it)

I'm aware of some of these underlinking issues with gcc on Linux, but right now should be fixed (at least the compilation should be working). I'm thinking in a more proper change. i.e. adding `target_link_libraries` to all sub-libraries (she, base, gfx, css, undo, etc.).

**Comment by winterheart** [comment]
Hello.
I'm using Gentoo Linux x86_64, gcc 4.8.4. I'm trying to compile aseprite with shared system packages (without third_party dir as possible). If you need, I can attach compile log for problem part.

**Comment by dacap** [comment]
OK, I'll create a special branch (named `link-fixes`) with dependencies between all libraries, could you pull it when it's available to test it? I'll comment this PR when I push it.
Thanks for your help!

**Comment by dacap** [comment]
I've just created [link-fixes](https://github.com/aseprite/aseprite/tree/link-fixes) branch. I hope it works. I've tested on Windows and Ubuntu 14.04 32bits. I'll see if it works correctly on Travis and test it on Mac this week.

**Comment by winterheart** [comment]
All good for me, link-fixes compiles without fatal errors.

**Comment by dacap** [comment]
Thanks for your help @winterheart, I've merged the branch to master so I'll close this PR.

**Pull request closed without merging**
