### PR TITLE
Fix bug when after pasting a color to the ColorBar Palette the ColorS…

### PR DESCRIPTION
**Pull request by Zeralith**
…elector is not updated properly

### CODE REVIEW

**Comment by dacap** [comment]
Hi @Zeralith, I cannot reproduce this bug. Is there a list of steps to reproduce the bug when the patch is not applied?

In case this patch is needed, I think something like this on `ColorBar::onPaletteViewPasteColors` would be preferred:

```diff
diff --git a/src/app/ui/color_bar.cpp b/src/app/ui/color_bar.cpp
index 649d5bf9d..960e98783 100644
--- a/src/app/ui/color_bar.cpp
+++ b/src/app/ui/color_bar.cpp
@@ -702,6 +702,7 @@ void ColorBar::onPaletteViewPasteColors(
   }
 
   setPalette(&newPalette, "Paste Colors");
+  invalidate();
 }
 
 app::Color ColorBar::onPaletteViewGetForegroundIndex()
```

**Comment by Zeralith** [comment]
Hi @dacap, running `invalidate()` is just not enough here. I tried this before. For some odd reason, running `setBounds(bounds())` is the only way I could seem to solve this.

Running `setBounds(bounds())` after the `setPalette(&newPalette, "Paste Colors");` line on `ColorBar::onPaletteViewPasteColors()` works as well, as you described.

To explain the bug, I will make a video and send it to you. It's a very nuanced bug to the untrained eye 😝

Stand-by.

**Comment by Zeralith** [comment]
@dacap, here you go! This video shows the bug & fix in action:

https://youtu.be/2pUV8VJSk-s

**Comment by Zeralith** [comment]
Hey @dacap, did you need me to do anything else with this PR, or were you going to edit it?

Did my video make sense describing the bug and the fix?

Thank you.

**Comment by dacap** [comment]
Hi @Zeralith, sorry I missed your PR for the release. I'll give a try in these days (and maybe find an alternative fix). My main issue with this patch is detecting the "Paste Colors" as:
```c++
  if (actionText == "Paste Colors") {
```

**Pull request closed without merging**
