### PR TITLE
New Palettes

### PR DESCRIPTION
**Pull request by Nsheppard01**
Made two minor formatting and white-space edits to the solarized palette.

### CODE REVIEW

**Comment by Nsheppard01** [comment]
This adds two new palettes and makes minor formatting and whitespace changes to several others.

**Comment by Nsheppard01** [comment]
Properly attributed the monokai palette and mad a bunch of nitpicky edits to the rest. They all use tabs instead of spaces, and start with either 
	GIMP Palette
	Name: <palettename>
	#
or
	GIMP Palette
	#
	# by authorname
	# http://www.example.com/
	#

**Comment by dacap** [comment]
Hi @Nsheppard01, I'll close this PR. Some points:

* Don't worry about white spaces in current palettes or `Name:` property, I'll add these properties in case the program starts using them.
* It looks like the solarize palette doesn't have a black entry in index 0
* I'll prefer one PR for each logic change (instead of adding several unrelated changes to one PR)
* I'm not quite sure to start adding a lot of palettes. I'll take a look to the x11 and monokai later, but I'd prefer pixel-art related palettes.

**Comment by Nsheppard01** [comment]
Okay, should I re-submit a pull request with just Monokai and X11?

I did kind of go overboard with whitespace.

**Comment by dacap** [comment]
That would be great @Nsheppard01!

**Pull request closed without merging**
