### PR TITLE
ARM build fixes

### PR DESCRIPTION
**Pull request by Zaryob**
Related with issue [#2630](https://github.com/aseprite/aseprite/issues/2630)

### CODE REVIEW

**Review by fabinshen — APPROVED** [review]
The change seems good and straightforward.

**Comment by SerenaLexis** [comment]
Please unsubscribe me ! I’m getting hundreds of emails that mean nothing to
me

**Review by Zaryob — COMMENTED** [review]
reviewed

**Comment by dacap** [comment]
Hi @Zaryob, from the patch it looks like we have to patch or update libcurl, but I saw that it doesn't include the curlbuild.h file anymore in its repository:
https://github.com/curl/curl/commit/73a2fcea0b4adea6ba342cd7ed1149782c214ae3

I think that we should convert the curl code into a submodule and use the latest version from it (and then patch libcurl if it's needed).

**Comment by Zaryob** [comment]
> Hi @Zaryob, from the patch it looks like we have to patch or update libcurl, but I saw that it doesn't include the curlbuild.h file anymore in its repository:
> [curl/curl@73a2fce](https://github.com/curl/curl/commit/73a2fcea0b4adea6ba342cd7ed1149782c214ae3)
> 
> I think that we should convert the curl code into a submodule and use the latest version from it (and then patch libcurl if it's needed).

Got it is a good new. This type of arm fix is needed for either raspi or Apple m1 macs
Good works.

**Pull request closed without merging**
