### PR TITLE
Fix cursor and selection size on 100% screen scale (fix 2869)

### PR DESCRIPTION
**Pull request by ruerob**
Fix suggestion for issue #2869.

I don't know if it is okay if everything is just scaled on the smallest screen scale, but I'm really satisfied with the sizes at 200%.

I changed:

- The size of the pen cursor by setting the scale to 2.
- The size of the selection cursor by adding scaling to the pixel putting. 
- The size of the selection by drawing the same selection one pixel right and down again.

I hope this is helpful and wish you a nice day.
ruerob

### CODE REVIEW

**Comment by dacap** [comment]
Hi @ruerob, thanks for your contribution, I think you could use the `guiscale()` to duplicate (or triplicate, etc.) the thick of each edge.

For `Editor::drawMask()` I guess `os::Paint::strokeWidth()` could be set.

**Comment by ruerob** [comment]
Hi @dacap, thanks for the reply!

I tried `os::Paint::strokeWidth()` but that messed up the marching ants.

I'll try `guiscale()` and see how it looks.

**Comment by ruerob** [comment]
With strokeWidth(2) the lines are two pixels thick but look like this:

image

On the upper edge, the upper pixels won't march at all, and the lower pixels are moving like expected. That doesn't look pretty in my eyes.

**Comment by ruerob** [comment]
Thank you @dacap!

Now I've added `ui::guiscale()` for scaling the select cursor.

**Comment by dacap** [comment]
Thanks @ruerob to dedicate some time to this issue, I'll review this today and see if merge part of it. The issue with the marching ants pattern looks that could be solved making the pattern bigger (by guiscale()), but that requires modifying the laf library too. We can leave that part for the future.

**Comment by dacap** [comment]
After reviewing this I think the resulting cursor (mainly for the selection tool) is not a desirable result:

Screenshot from 2022-09-28 17-45-22

Also I'm not sure about changing the marching ant effect/path stroke width.

Screenshot from 2022-09-28 17-48-16

I'll left this PR to be reviewed in the future but we don't have a resolution for this yet.

**Comment by dacap** [comment]
I have rebased the changes and an extra #include to make it work https://github.com/dacap/aseprite/tree/ruerob-fix-2869

**Comment by dacap** [comment]
Thinking about this option, as cursors are created [using "get pixel" from the screen](https://github.com/aseprite/aseprite/blob/4981f05f0badff06d43cc47d6cd63861225f77db/src/app/ui/editor/brush_preview.cpp#L532), and then doing a negative using black or white, we cannot make the current cursor bigger (as this would require [a bigger cache of cursors](https://github.com/aseprite/aseprite/blob/4981f05f0badff06d43cc47d6cd63861225f77db/src/app/ui/editor/brush_preview.cpp#L61)), we should use another kind of cursor in these cases.

**Comment by dacap** [comment]
Closing this as we need a different approach.

**Pull request closed without merging**
